dist: trusty
language: cpp
compiler: gcc
notifications:
  email: false
env:
  global:
    # EM_USE_GLOBAL_CACHE=1 tells emscripten to use precompiled libraries from
    # the emscripten-libs-asmjs package. This speeds up the build significantly.
    - EM_USE_GLOBAL_CACHE=1
before_install:
 - sudo apt-get install libasound2-dev
jobs:
  include:
    - stage: Hardware Platform (STM32)
      script:
      - make setup_stm32 && (cd build/stm32/debug && make) && (cd build/stm32/release && make) && make deploy
      # Deploy to github releases
      deploy:
        provider: releases
        api_key: "h+/G8sNYseKnvkuI3hnMX2XPF5Nw+vucYI66FFZ1lY1NHH8WKqjwg/R76M1gaLMWVHNOytA16G7IUJgDsqBfHgxoS5ALvLr/Tmc2ETL2Qk31fN0EPDUSBgOGVFKZpN3bw/++R9m7Npp/7jnKFRIhUwWPCWow6JHxqY4awiqPSFXct1JZs4O9WSJMalcJcypbf7ygJxWhdEvjEUI6+KogY8qhncT/rOZTqYUzJzlYAPE7Oe2H7HW26lrgAKBWjyFcS0H5Bpz8hiSZqI2AInOjNUwqm91zA0YlJt5jEr1Q2ZsraOcEPnuq1yurnbLb5dE+EV35U29MDmJeyJseLBcubC7OPdOOCcewrRB1n5yxGU93oe4oGUx7f8YaSoSva3eN9XnBmGAfG+XMWazhr/7vqp3qWmA4LMP5nAyRl2Npz4TtJEc8ip8QUXEFxE19o9/YD8YWCUK/MB8NNCbzceCOYH5hoc6spxcaJq8qLbVrUVbZV2E4v6SIzwFohS7EGKYd/XXKmlvpiQ+CEr+y0osJ0PPuLV0EyQShqBFGBFmDmvjcVNdfbTZuclBvuDewgyffo0STKZ9rIp+TYf/z1bCeJLodAhnZIxMPCcfe+JfwhE36PKkaTgauV/FsjaAXdZI6Y8MuDEtxUAJbPkNvJYXHHAEnutWofSDw7X8KDbbgcys="
        file_glob: true
        file: build/deploy/*
        skip_cleanup: true
    - stage: Simulation Platform (Linux)
      script:
      # Simulation target requires recent versions of SDL2, SDL2_image and SDL2_ttf not available as packages
      - wget https://www.libsdl.org/release/SDL2-2.0.7.tar.gz
      - tar -xf SDL2-2.0.7.tar.gz
      - (cd SDL2-2.0.7 && ./configure && make && sudo make install)
      - wget https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.2.tar.gz
      - tar -xf SDL2_image-2.0.2.tar.gz
      - (cd SDL2_image-2.0.2 && ./configure --disable-png && make && sudo make install)
      - wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.tar.gz
      - tar -xf SDL2_ttf-2.0.14.tar.gz
      - (cd SDL2_ttf-2.0.14 && ./configure && make && sudo make install)
      - make setup_sim && (cd build/sim/debug && make) && (cd build/sim/release && make)
    - stage: Simulation Platform (WebAssembly)
      script:
      # Download and verify alpine-chroot-install script
      - wget https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.6.0/alpine-chroot-install
          && echo 'a827a4ba3d0817e7c88bae17fe34e50204983d1e  alpine-chroot-install' | sha1sum -c
      # Install Alpine Linux into /alpine and prepare there a chroot environment;
      # add testing repository and install packages for Emscripten.
      - sudo sh alpine-chroot-install -b v3.6
          -r 'https://nl.alpinelinux.org/alpine/edge/testing'
          -p 'emscripten emscripten-libs-wasm binaryen closure-compiler make cmake'
          -k 'CI TRAVIS_.* EM_.*'
      # Setup a script to run in chroot for emscripten build
      - printf '#!/bin/sh\nexport EMSCRIPTEN=/usr/share/emscripten\nmake setup_www\n(cd build/sim/www && make)' > build-www.sh
      - chmod a+x build-www.sh
      # Build
      - /alpine/enter-chroot -u $USER ./build-www.sh
